{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Bot Score",
    "version" : "2024-07-16T21:03:13Z"
  },
  "servers" : [ {
    "url" : "https://api.euc1.nonprod.insighttech.ai/{basePath}",
    "variables" : {
      "basePath" : {
        "default" : "develop/bscore"
      }
    }
  } ],
  "paths" : {
    "/bscore/{bookmaker}/{subbookmaker}/list" : {
      "get" : {
        "tags" : [ "Endpoints" ],
        "summary" : "Retrieve All Bot Scores",
        "description" : "Fetches Bot Scores for all accounts associated with a specific bookmaker and sub-bookmaker. If there are multiple pages of results, the response may include a lastEvaluatedKey for pagination.",
        "operationId" : "Bot Score List",
        "parameters" : [ {
          "name" : "lastKey",
          "in" : "query",
          "description" : "The response will start from the provided lastKey, which matches the lastEvaluatedKey from the previous call.",
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "bookmaker",
          "in" : "path",
          "required" : true,
          "description": "Identifier for the bookmaker. Generated by Sportradar, contact your OAM or CI engineer in case of any issues with obtaining the correct value.",
          "schema" : {
            "type" : "string"
          },
          "example" : "21661"
        }, {
          "name" : "subbookmaker",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "example" : "1011",
          "description" : "Identifier for the sub-bookmaker. Generated by Sportradar, contact your OAM or CI engineer in case of any issues with obtaining the correct value. Value * retrieves all data for a bookmaker." 
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BotScoreResponse"
                },
                "example" : {
                    "requestId": "",
                    "responseStatus": "SUCCESSFUL",
                    "responseMessage": "Number of items found: 2",
                    "queryExecutionTime": 9,
                    "lastEvaluatedKey": {},
                    "responseItem": {
                      "customers": [
                        {
                          "C": {
                            "srcId": "BK-24:BK-24-4::::C10024",
                            "bscore": "0.24",
                            "id": "C10024"
                          }
                        },
                        {
                          "C": {
                            "srcId": "BK-24:BK-24-4::::C10074",
                            "bscore": "0.74",
                            "id": "C10074"
                          }
                        }
                      ]
                    }
                  }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized",
            "content" : {
                "application/json" : {
                  "schema" : {
                    "required" : [ "message" ],
                       "type" : "object",
                       "properties" : {
                          "message" : {
                          "type" : "string",
                          "description" : "The client must authenticate itself to get the requested response."
                            }
                          }
                     },
                  "example" : {
                        "message": "Authorization error, please contact support."
                }
              }
            }
          },
          "403" : {
            "description" : "Forbidden",
            "content" : {
                "application/json" : {
                  "schema" : {
                    "required" : [ "message" ],
                       "type" : "object",
                       "properties" : {
                          "message" : {
                          "type" : "string",
                          "description" : "The client does not have access rights to the content."
                            }
                          }
                     },
                  "example" : {
                        "message": "You do not have permission to access this resource."
                }
              }
            }
          },
          "500" : {
            "description" : "Internal Server Error",
            "content" : {
                "application/json" : {
                  "schema" : {
                    "required" : [ "message" ],
                       "type" : "object",
                       "properties" : {
                          "message" : {
                          "type" : "string",
                          "description" : "The server has encountered a situation it doesn't know how to handle."
                            }
                          }
                     },
                  "example" : {
                        "message": "Internal server error, please contact support."
                }
              }
            }
          }
        },
        "security" : [ {
          "mts-insight-tech-bot-score-authorizer" : [ ]
        } ]
      }
    },
    "/bscore/{bookmaker}/{subbookmaker}/source" : {
      "get" : {
        "tags" : [ "Endpoints" ],
        "summary" : "Retrieve Bot Scores for Specific Accounts",
        "description" : "Fetches Bot Scores for a specified list of account IDs under a given bookmaker and sub-bookmaker. If there are multiple pages of results, the response may include a lastEvaluatedKey for pagination.",
        "operationId" : "Bot Score Source",
        "parameters" : [ {
          "name" : "customer",
          "in" : "query",
          "description" : "Comma-separated list of account IDs for which to retrieve data. Each account ID should belong to the specified bookmaker and sub-bookmaker.",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "bookmaker",
          "in" : "path",
          "required" : true,
          "description" : "Identifier for the bookmaker. Generated by Sportradar, contact your OAM or CI engineer in case of any issues with obtaining the correct value.",
          "schema" : {
            "type" : "string"
          },
          "example" : "21661"
        }, {
          "name" : "subbookmaker",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "example" : "1011",
          "description" : "Identifier for the sub-bookmaker. Generated by Sportradar, contact your OAM or CI engineer in case of any issues with obtaining the correct value. Value * retrieves all data for a bookmaker." 
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BotScoreResponse"
                },
                "example" : {
                    "requestId": "",
                    "responseStatus": "SUCCESSFUL",
                    "responseMessage": "Number of items found: 2",
                    "queryExecutionTime": 9,
                    "lastEvaluatedKey": {},
                    "responseItem": {
                      "customers": [
                        {
                          "C": {
                            "srcId": "BK-24:BK-24-4::::C10024",
                            "bscore": "0.24",
                            "id": "C10024"
                          }
                        },
                        {
                          "C": {
                            "srcId": "BK-24:BK-24-4::::C10074",
                            "bscore": "0.74",
                            "id": "C10074"
                          }
                        }
                      ]
                    }
                  }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized",
            "content" : {
                "application/json" : {
                  "schema" : {
                    "required" : [ "message" ],
                       "type" : "object",
                       "properties" : {
                          "message" : {
                          "type" : "string",
                          "description" : "The client must authenticate itself to get the requested response."
                            }
                          }
                     },
                  "example" : {
                        "message": "Authorization error, please contact support."
                }
              }
            }
          },
          "403" : {
            "description" : "Forbidden",
            "content" : {
                "application/json" : {
                  "schema" : {
                    "required" : [ "message" ],
                       "type" : "object",
                       "properties" : {
                          "message" : {
                          "type" : "string",
                          "description" : "The client does not have access rights to the content."
                            }
                          }
                     },
                  "example" : {
                        "message": "You do not have permission to access this resource."
                }
              }
            }
          },
          "500" : {
            "description" : "Internal Server Error",
            "content" : {
                "application/json" : {
                  "schema" : {
                    "required" : [ "message" ],
                       "type" : "object",
                       "properties" : {
                          "message" : {
                          "type" : "string",
                          "description" : "The server has encountered a situation it doesn't know how to handle."
                            }
                          }
                     },
                  "example" : {
                        "message": "Internal server error, please contact support."
                }
              }
            }
          }
        },
        "security" : [ {
          "mts-insight-tech-bot-score-authorizer" : [ ]
        } ]
      }
    },
    "/bscore/{bookmaker}/{subbookmaker}/range" : {
      "get" : {
        "tags" : [ "Endpoints" ],
        "summary" : "Retrieve Bot Scores in a Range",
        "description" : "Fetches Bot Scores for accounts under a bookmaker and sub-bookmaker whose scores fall within a specified range. If there are multiple pages of results, the response may include a lastEvaluatedKey for pagination.",
        "operationId" : "Bot Score Range",
        "parameters" : [ {
          "name" : "lower",
          "in" : "query",
          "description" : "Lower threshold of the score range to retrieve data for. At least one of the lower/higher query parameters is required.",
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "higher",
          "in" : "query",
          "description" : "Higher threshold of the score range to retrieve data for. At least one of the lower/higher query parameters is required.",
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "startKey",
          "in" : "query",
          "description" : "The response will resume from the provided startKey, which matches the lastEvaluatedKey from the previous call.",
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "bookmaker",
          "in" : "path",
          "required" : true,
          "description" : "Identifier for the bookmaker. Generated by Sportradar, contact your OAM or CI engineer in case of any issues with obtaining the correct value.",
          "schema" : {
            "type" : "string"
          },
          "example" : "21661"
        }, {
          "name" : "subbookmaker",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "example" : "1011",
          "description" : "Identifier for the sub-bookmaker. Generated by Sportradar, contact your OAM or CI engineer in case of any issues with obtaining the correct value. Value * retrieves all data for a bookmaker." 
        } ],
        "responses" : {
          "200" : {
            "description" : "Successful Request",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/BotScoreResponse"
                },
                "example" : {
                    "requestId": "",
                    "responseStatus": "SUCCESSFUL",
                    "responseMessage": "Number of items found: 2",
                    "queryExecutionTime": 9,
                    "lastEvaluatedKey": {},
                    "responseItem": {
                      "customers": [
                        {
                          "C": {
                            "srcId": "BK-24:BK-24-4::::C10024",
                            "bscore": "0.24",
                            "id": "C10024"
                          }
                        },
                        {
                          "C": {
                            "srcId": "BK-24:BK-24-4::::C10074",
                            "bscore": "0.74",
                            "id": "C10074"
                          }
                        }
                      ]
                    }
                  }
              }
            }
          },
          "400" : {
            "description": "Bad Request - The server could not understand the request due to invalid syntax.",
            "content": {
              "application/json": {
                "schema": {
                  "required": ["responseStatus", "responseMessage", "queryExecutionTime"],
                  "type": "object",
                  "properties": {
                    "responseStatus": {
                      "type": "string",
                      "description": "Status of the response"
                    },
                    "responseMessage": {
                      "type": "string",
                      "description": "Message describing the response status"
                    },
                    "queryExecutionTime": {
                      "type": "integer",
                      "description": "Query execution time in milliseconds"
                    }
                  }
                },
                "example": {
                  "responseStatus": "VALIDATION_FAILED",
                  "responseMessage": "For a range query, the lower value should be smaller than the higher value.",
                  "queryExecutionTime": 0
                }
              }
            }
          },
          "401" : {
            "description" : "Unauthorized",
            "content" : {
                "application/json" : {
                  "schema" : {
                    "required" : [ "message" ],
                       "type" : "object",
                       "properties" : {
                          "message" : {
                          "type" : "string",
                          "description" : "The client must authenticate itself to get the requested response."
                            }
                          }
                     },
                  "example" : {
                        "message": "Authorization error, please contact support."
                }
              }
            }
          },
          "403" : {
            "description" : "Forbidden",
            "content" : {
                "application/json" : {
                  "schema" : {
                    "required" : [ "message" ],
                       "type" : "object",
                       "properties" : {
                          "message" : {
                          "type" : "string",
                          "description" : "The client does not have access rights to the content."
                            }
                          }
                     },
                  "example" : {
                        "message": "You do not have permission to access this resource."
                }
              }
            }
          },
          "500" : {
            "description" : "Internal Server Error",
            "content" : {
                "application/json" : {
                  "schema" : {
                    "required" : [ "message" ],
                       "type" : "object",
                       "properties" : {
                          "message" : {
                          "type" : "string",
                          "description" : "The server has encountered a situation it doesn't know how to handle."
                            }
                          }
                     },
                  "example" : {
                        "message": "Internal server error, please contact support."
                }
              }
            }
          }
        },
        "security" : [ {
          "mts-insight-tech-bot-score-authorizer" : [ ]
        } ]
      }
    }
  },
  "components" : {
    "schemas" : {
      "BotScoreResponseResponseItem" : {
        "type" : "object",
        "properties" : {
          "customers" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BotScoreResponseResponseItemCustomersItem"
            }
          }
        },
        "additionalProperties" : false
      },
      "BotScoreResponseResponseItemCustomersItem" : {
        "required" : [ "C" ],
        "type" : "object",
        "properties" : {
          "C" : {
            "$ref" : "#/components/schemas/BotScoreResponseResponseItemCustomersItemC"
          }
        },
        "additionalProperties" : false
      },
      "BotScoreResponseResponseItemCustomersItemC" : {
        "required" : [ "bscore", "id", "srcId" ],
        "type" : "object",
        "properties" : {
          "bscore" : {
            "type" : "string",
            "description" : "Bot Score value (between 0.00 and 1.00)" 
          },
          "id" : {
            "type" : "string",
            "description" : "ID of customer"
          },
          "srcId" : {
            "type" : "string",
            "description" : "Source ID containing bookmaker, sub-bookmaker and customer IDs" 
          }
        },
        "additionalProperties" : false
      },
      "BotScoreResponse" : {
        "required" : [ "queryExecutionTime", "requestId", "responseItem", "responseMessage", "responseStatus" ],
        "type" : "object",
        "properties" : {
          "lastEvaluatedKey" : {
            "type" : "string",
            "description" : "Used if response has more than one page - the first response has a lastEvaluatedKey that is used as the startKey in request for the next page"
          },
          "queryExecutionTime" : {
            "type" : "integer",
            "description" : "Query execution time in milliseconds"
          },
          "requestId" : {
            "type" : "string",
            "description" : "ID of the request"
          },
          "responseItem" : {
            "$ref" : "#/components/schemas/BotScoreResponseResponseItem"
          },
          "responseMessage" : {
            "type" : "string",
            "description" : "Number of items found based on search criteria"
          },
          "responseStatus" : {
            "type" : "string",
            "enum" : [ "SUCCESSFUL", "VALIDATION_FAILED", "ERROR", "KEY_NOT_FOUND" ]
          }
        }
      }
    },
    "securitySchemes" : {
      "mts-insight-tech-bot-score-authorizer" : {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
